title: Tobias Schr√∂der
permalink: /:title/
#theme: jekyll-theme-minimal
remote_theme: "mmistakes/minimal-mistakes@4.27.3"

nav:
  - name: "Home"
    link: "/"
  - name: "Projects"
    link: "/projects"

#header_pages:
#  - about.md
#  - projects.md
